
export const audioSlider = [
    {
        background: 'no_background',
        category: 'সফলতার গল্প',
        sliderData: [
            {
                image: '/audioBook/demoCatImage/cover 1.jpg',
                title: 'তিন গোয়েন্দা',
                writer: 'রকিব হাসান',
                voice: 'রকিব হাসান তুষার',
                duration: '১:৪১ মিনিট',
            },
            {
                image: '/audioBook/audio-slider/audio-slider-img-1.png',
                title: 'তিন গোয়েন্দা',
                writer: 'রকিব হাসান',
                voice: 'রকিব হাসান তুষার',
                duration: '১:৪১ মিনিট',
            },
            {
                image: '/audioBook/audio-slider/audio-slider-img-2.png',
                title: 'তিন গোয়েন্দা',
                writer: 'রকিব হাসান',
                voice: 'রকিব হাসান তুষার',
                duration: '১:৪১ মিনিট',
            },
            {
                image: '/audioBook/audio-slider/audio-slider-img-3.png',
                title: 'তিন গোয়েন্দা',
                writer: 'রকিব হাসান',
                voice: 'রকিব হাসান তুষার',
                duration: '১:৪১ মিনিট',
            },
            {
                image: '/audioBook/audio-slider/audio-slider-img-4.png',
                title: 'তিন গোয়েন্দা',
                writer: 'রকিব হাসান',
                voice: 'রকিব হাসান তুষার',
                duration: '১:৪১ মিনিট',
            },
            {
                image: '/audioBook/demoCatImage/cover 1.jpg',
                title: 'তিন গোয়েন্দা',
                writer: 'রকিব হাসান',
                voice: 'রকিব হাসান তুষার',
                duration: '১:৪১ মিনিট',
            },
            {
                image: '/audioBook/audio-slider/audio-slider-img-1.png',
                title: 'তিন গোয়েন্দা',
                writer: 'রকিব হাসান',
                voice: 'রকিব হাসান তুষার',
                duration: '১:৪১ মিনিট',
            },
        ]
    },
    {
        background: 'no_background',
        category: 'গল্প',
        sliderData: [
            {
                image: '/audioBook/demoCatImage/cover 1.jpg',
                title: 'তিন গোয়েন্দা',
                writer: 'রকিব হাসান',
                voice: 'রকিব হাসান তুষার',
                duration: '১:৪১ মিনিট',
            },
            {
                image: '/audioBook/audio-slider/audio-slider-img-1.png',
                title: 'তিন গোয়েন্দা',
                writer: 'রকিব হাসান',
                voice: 'রকিব হাসান তুষার',
                duration: '১:৪১ মিনিট',
            },
            {
                image: '/audioBook/audio-slider/audio-slider-img-2.png',
                title: 'তিন গোয়েন্দা',
                writer: 'রকিব হাসান',
                voice: 'রকিব হাসান তুষার',
                duration: '১:৪১ মিনিট',
            },
            {
                image: '/audioBook/audio-slider/audio-slider-img-3.png',
                title: 'তিন গোয়েন্দা',
                writer: 'রকিব হাসান',
                voice: 'রকিব হাসান তুষার',
                duration: '১:৪১ মিনিট',
            },
            {
                image: '/audioBook/audio-slider/audio-slider-img-4.png',
                title: 'তিন গোয়েন্দা',
                writer: 'রকিব হাসান',
                voice: 'রকিব হাসান তুষার',
                duration: '১:৪১ মিনিট',
            },
            {
                image: '/audioBook/demoCatImage/cover 1.jpg',
                title: 'তিন গোয়েন্দা',
                writer: 'রকিব হাসান',
                voice: 'রকিব হাসান তুষার',
                duration: '১:৪১ মিনিট',
            },
            {
                image: '/audioBook/audio-slider/audio-slider-img-1.png',
                title: 'তিন গোয়েন্দা',
                writer: 'রকিব হাসান',
                voice: 'রকিব হাসান তুষার',
                duration: '১:৪১ মিনিট',
            },
        ]
    },
    {
        background: 'background',
        category: 'Science Fiction',
        sliderData: [
            {
                image: '/audioBook/audio-slider/bgSliderImg.png',
                title: 'তিন গোয়েন্দা',
                writer: 'রকিব হাসান',
                voice: 'রকিব হাসান তুষার',
                duration: '১:৪১ মিনিট',
                color: '#00736B',
            },
            {
                image: '/audioBook/audio-slider/bgSliderImg.png',
                title: 'তিন গোয়েন্দা',
                writer: 'রকিব হাসান',
                voice: 'রকিব হাসান তুষার',
                duration: '১:৪১ মিনিট',
                color: '#E43727',
            },
            {
                image: '/audioBook/audio-slider/bgSliderImg.png',
                title: 'তিন গোয়েন্দা',
                writer: 'রকিব হাসান',
                voice: 'রকিব হাসান তুষার',
                duration: '১:৪১ মিনিট',
                color: '#FFBF00',
            },
            {
                image: '/audioBook/audio-slider/bgSliderImg.png',
                title: 'তিন গোয়েন্দা',
                writer: 'রকিব হাসান',
                voice: 'রকিব হাসান তুষার',
                duration: '১:৪১ মিনিট',
                color: '#59C1B9',
            },
            {
                image: '/audioBook/audio-slider/bgSliderImg.png',
                title: 'তিন গোয়েন্দা',
                writer: 'রকিব হাসান',
                voice: 'রকিব হাসান তুষার',
                duration: '১:৪১ মিনিট',
                color: '#585EDF',
            },
            {
                image: '/audioBook/audio-slider/bgSliderImg.png',
                title: 'তিন গোয়েন্দা',
                writer: 'রকিব হাসান',
                voice: 'রকিব হাসান তুষার',
                duration: '১:৪১ মিনিট',
                color: '#E13426',
            },
            {
                image: '/audioBook/audio-slider/bgSliderImg.png',
                title: 'তিন গোয়েন্দা',
                writer: 'রকিব হাসান',
                voice: 'রকিব হাসান তুষার',
                duration: '১:৪১ মিনিট',
                color: '#D35400',
            },
        ]
    },
    {
        background: 'no_background',
        category: 'রোমান্টিক',
        sliderData: [
            {
                image: '/audioBook/demoCatImage/cover 1.jpg',
                title: 'তিন গোয়েন্দা',
                writer: 'রকিব হাসান',
                voice: 'রকিব হাসান তুষার',
                duration: '১:৪১ মিনিট',
            },
            {
                image: '/audioBook/audio-slider/audio-slider-img-1.png',
                title: 'তিন গোয়েন্দা',
                writer: 'রকিব হাসান',
                voice: 'রকিব হাসান তুষার',
                duration: '১:৪১ মিনিট',
            },
            {
                image: '/audioBook/audio-slider/audio-slider-img-2.png',
                title: 'তিন গোয়েন্দা',
                writer: 'রকিব হাসান',
                voice: 'রকিব হাসান তুষার',
                duration: '১:৪১ মিনিট',
            },
            {
                image: '/audioBook/audio-slider/audio-slider-img-3.png',
                title: 'তিন গোয়েন্দা',
                writer: 'রকিব হাসান',
                voice: 'রকিব হাসান তুষার',
                duration: '১:৪১ মিনিট',
            },
            {
                image: '/audioBook/audio-slider/audio-slider-img-4.png',
                title: 'তিন গোয়েন্দা',
                writer: 'রকিব হাসান',
                voice: 'রকিব হাসান তুষার',
                duration: '১:৪১ মিনিট',
            },
            {
                image: '/audioBook/demoCatImage/cover 1.jpg',
                title: 'তিন গোয়েন্দা',
                writer: 'রকিব হাসান',
                voice: 'রকিব হাসান তুষার',
                duration: '১:৪১ মিনিট',
            },
            {
                image: '/audioBook/audio-slider/audio-slider-img-1.png',
                title: 'তিন গোয়েন্দা',
                writer: 'রকিব হাসান',
                voice: 'রকিব হাসান তুষার',
                duration: '১:৪১ মিনিট',
            },
        ]
    },
    {
        background: 'background',
        category: 'ইতিহাস',
        sliderData: [
            {
                image: '/audioBook/audio-slider/bgSliderImg.png',
                title: 'তিন গোয়েন্দা',
                writer: 'রকিব হাসান',
                voice: 'রকিব হাসান তুষার',
                duration: '১:৪১ মিনিট',
                color: '#00736B',
            },
            {
                image: '/audioBook/audio-slider/bgSliderImg.png',
                title: 'তিন গোয়েন্দা',
                writer: 'রকিব হাসান',
                voice: 'রকিব হাসান তুষার',
                duration: '১:৪১ মিনিট',
                color: '#E43727',
            },
            {
                image: '/audioBook/audio-slider/bgSliderImg.png',
                title: 'তিন গোয়েন্দা',
                writer: 'রকিব হাসান',
                voice: 'রকিব হাসান তুষার',
                duration: '১:৪১ মিনিট',
                color: '#FFBF00',
            },
            {
                image: '/audioBook/audio-slider/bgSliderImg.png',
                title: 'তিন গোয়েন্দা',
                writer: 'রকিব হাসান',
                voice: 'রকিব হাসান তুষার',
                duration: '১:৪১ মিনিট',
                color: '#59C1B9',
            },
            {
                image: '/audioBook/audio-slider/bgSliderImg.png',
                title: 'তিন গোয়েন্দা',
                writer: 'রকিব হাসান',
                voice: 'রকিব হাসান তুষার',
                duration: '১:৪১ মিনিট',
                color: '#585EDF',
            },
            {
                image: '/audioBook/audio-slider/bgSliderImg.png',
                title: 'তিন গোয়েন্দা',
                writer: 'রকিব হাসান',
                voice: 'রকিব হাসান তুষার',
                duration: '১:৪১ মিনিট',
                color: '#E13426',
            },
            {
                image: '/audioBook/audio-slider/bgSliderImg.png',
                title: 'তিন গোয়েন্দা',
                writer: 'রকিব হাসান',
                voice: 'রকিব হাসান তুষার',
                duration: '১:৪১ মিনিট',
                color: '#D35400',
            },
        ]
    },
    {
        background: 'no_background',
        category: 'সফলতার গল্প',
        sliderData: [
            {
                image: '/audioBook/demoCatImage/cover 1.jpg',
                title: 'তিন গোয়েন্দা',
                writer: 'রকিব হাসান',
                voice: 'রকিব হাসান তুষার',
                duration: '১:৪১ মিনিট',
            },
            {
                image: '/audioBook/audio-slider/audio-slider-img-1.png',
                title: 'তিন গোয়েন্দা',
                writer: 'রকিব হাসান',
                voice: 'রকিব হাসান তুষার',
                duration: '১:৪১ মিনিট',
            },
            {
                image: '/audioBook/audio-slider/audio-slider-img-2.png',
                title: 'তিন গোয়েন্দা',
                writer: 'রকিব হাসান',
                voice: 'রকিব হাসান তুষার',
                duration: '১:৪১ মিনিট',
            },
            {
                image: '/audioBook/audio-slider/audio-slider-img-3.png',
                title: 'তিন গোয়েন্দা',
                writer: 'রকিব হাসান',
                voice: 'রকিব হাসান তুষার',
                duration: '১:৪১ মিনিট',
            },
            {
                image: '/audioBook/audio-slider/audio-slider-img-4.png',
                title: 'তিন গোয়েন্দা',
                writer: 'রকিব হাসান',
                voice: 'রকিব হাসান তুষার',
                duration: '১:৪১ মিনিট',
            },
            {
                image: '/audioBook/demoCatImage/cover 1.jpg',
                title: 'তিন গোয়েন্দা',
                writer: 'রকিব হাসান',
                voice: 'রকিব হাসান তুষার',
                duration: '১:৪১ মিনিট',
            },
            {
                image: '/audioBook/audio-slider/audio-slider-img-1.png',
                title: 'তিন গোয়েন্দা',
                writer: 'রকিব হাসান',
                voice: 'রকিব হাসান তুষার',
                duration: '১:৪১ মিনিট',
            },
        ]
    },
    {
        background: 'background',
        category: 'ইতিহাস',
        sliderData: [
            {
                image: '/audioBook/audio-slider/bgSliderImg.png',
                title: 'তিন গোয়েন্দা',
                writer: 'রকিব হাসান',
                voice: 'রকিব হাসান তুষার',
                duration: '১:৪১ মিনিট',
                color: '#00736B',
            },
            {
                image: '/audioBook/audio-slider/bgSliderImg.png',
                title: 'তিন গোয়েন্দা',
                writer: 'রকিব হাসান',
                voice: 'রকিব হাসান তুষার',
                duration: '১:৪১ মিনিট',
                color: '#E43727',
            },
            {
                image: '/audioBook/audio-slider/bgSliderImg.png',
                title: 'তিন গোয়েন্দা',
                writer: 'রকিব হাসান',
                voice: 'রকিব হাসান তুষার',
                duration: '১:৪১ মিনিট',
                color: '#FFBF00',
            },
            {
                image: '/audioBook/audio-slider/bgSliderImg.png',
                title: 'তিন গোয়েন্দা',
                writer: 'রকিব হাসান',
                voice: 'রকিব হাসান তুষার',
                duration: '১:৪১ মিনিট',
                color: '#59C1B9',
            },
            {
                image: '/audioBook/audio-slider/bgSliderImg.png',
                title: 'তিন গোয়েন্দা',
                writer: 'রকিব হাসান',
                voice: 'রকিব হাসান তুষার',
                duration: '১:৪১ মিনিট',
                color: '#585EDF',
            },
            {
                image: '/audioBook/audio-slider/bgSliderImg.png',
                title: 'তিন গোয়েন্দা',
                writer: 'রকিব হাসান',
                voice: 'রকিব হাসান তুষার',
                duration: '১:৪১ মিনিট',
                color: '#E13426',
            },
            {
                image: '/audioBook/audio-slider/bgSliderImg.png',
                title: 'তিন গোয়েন্দা',
                writer: 'রকিব হাসান',
                voice: 'রকিব হাসান তুষার',
                duration: '১:৪১ মিনিট',
                color: '#D35400',
            },
        ]
    },
]
