
export const audioList = {
    category: 'সমসাময়িক',
    data:
     [
        {
            image: '/audioBook/demoCatImage/cover 1.jpg',
            title: 'তিন গোয়েন্দা',
            writer: 'রকিব হাসান',
            voice: 'রকিব হাসান তুষার',
            duration: '১:৪১ মিনিট',
        },
        {
            image: '/audioBook/audio-slider/audio-slider-img-1.png',
            title: 'তিন গোয়েন্দা',
            writer: 'রকিব হাসান',
            voice: 'রকিব হাসান তুষার',
            duration: '১:৪১ মিনিট',
        },
        {
            image: '/audioBook/audio-slider/audio-slider-img-2.png',
            title: 'তিন গোয়েন্দা',
            writer: 'রকিব হাসান',
            voice: 'রকিব হাসান তুষার',
            duration: '১:৪১ মিনিট',
        },
        {
            image: '/audioBook/audio-slider/audio-slider-img-3.png',
            title: 'তিন গোয়েন্দা',
            writer: 'রকিব হাসান',
            voice: 'রকিব হাসান তুষার',
            duration: '১:৪১ মিনিট',
        },
        {
            image: '/audioBook/audio-slider/audio-slider-img-4.png',
            title: 'তিন গোয়েন্দা',
            writer: 'রকিব হাসান',
            voice: 'রকিব হাসান তুষার',
            duration: '১:৪১ মিনিট',
        },
        {
            image: '/audioBook/demoCatImage/cover 1.jpg',
            title: 'তিন গোয়েন্দা',
            writer: 'রকিব হাসান',
            voice: 'রকিব হাসান তুষার',
            duration: '১:৪১ মিনিট',
        },
        {
            image: '/audioBook/audio-slider/audio-slider-img-1.png',
            title: 'তিন গোয়েন্দা',
            writer: 'রকিব হাসান',
            voice: 'রকিব হাসান তুষার',
            duration: '১:৪১ মিনিট',
        },
        {
            image: '/audioBook/demoCatImage/cover 1.jpg',
            title: 'তিন গোয়েন্দা',
            writer: 'রকিব হাসান',
            voice: 'রকিব হাসান তুষার',
            duration: '১:৪১ মিনিট',
        },
        {
            image: '/audioBook/audio-slider/audio-slider-img-1.png',
            title: 'তিন গোয়েন্দা',
            writer: 'রকিব হাসান',
            voice: 'রকিব হাসান তুষার',
            duration: '১:৪১ মিনিট',
        },
        {
            image: '/audioBook/audio-slider/audio-slider-img-2.png',
            title: 'তিন গোয়েন্দা',
            writer: 'রকিব হাসান',
            voice: 'রকিব হাসান তুষার',
            duration: '১:৪১ মিনিট',
        },
        {
            image: '/audioBook/audio-slider/audio-slider-img-3.png',
            title: 'তিন গোয়েন্দা',
            writer: 'রকিব হাসান',
            voice: 'রকিব হাসান তুষার',
            duration: '১:৪১ মিনিট',
        },
        {
            image: '/audioBook/audio-slider/audio-slider-img-4.png',
            title: 'তিন গোয়েন্দা',
            writer: 'রকিব হাসান',
            voice: 'রকিব হাসান তুষার',
            duration: '১:৪১ মিনিট',
        },
        {
            image: '/audioBook/demoCatImage/cover 1.jpg',
            title: 'তিন গোয়েন্দা',
            writer: 'রকিব হাসান',
            voice: 'রকিব হাসান তুষার',
            duration: '১:৪১ মিনিট',
        },
        {
            image: '/audioBook/audio-slider/audio-slider-img-1.png',
            title: 'তিন গোয়েন্দা',
            writer: 'রকিব হাসান',
            voice: 'রকিব হাসান তুষার',
            duration: '১:৪১ মিনিট',
        },
        {
            image: '/audioBook/demoCatImage/cover 1.jpg',
            title: 'তিন গোয়েন্দা',
            writer: 'রকিব হাসান',
            voice: 'রকিব হাসান তুষার',
            duration: '১:৪১ মিনিট',
        },
        {
            image: '/audioBook/audio-slider/audio-slider-img-1.png',
            title: 'তিন গোয়েন্দা',
            writer: 'রকিব হাসান',
            voice: 'রকিব হাসান তুষার',
            duration: '১:৪১ মিনিট',
        },
        {
            image: '/audioBook/audio-slider/audio-slider-img-2.png',
            title: 'তিন গোয়েন্দা',
            writer: 'রকিব হাসান',
            voice: 'রকিব হাসান তুষার',
            duration: '১:৪১ মিনিট',
        },
        {
            image: '/audioBook/audio-slider/audio-slider-img-3.png',
            title: 'তিন গোয়েন্দা',
            writer: 'রকিব হাসান',
            voice: 'রকিব হাসান তুষার',
            duration: '১:৪১ মিনিট',
        },
        {
            image: '/audioBook/audio-slider/audio-slider-img-4.png',
            title: 'তিন গোয়েন্দা',
            writer: 'রকিব হাসান',
            voice: 'রকিব হাসান তুষার',
            duration: '১:৪১ মিনিট',
        },
        {
            image: '/audioBook/demoCatImage/cover 1.jpg',
            title: 'তিন গোয়েন্দা',
            writer: 'রকিব হাসান',
            voice: 'রকিব হাসান তুষার',
            duration: '১:৪১ মিনিট',
        },
        {
            image: '/audioBook/audio-slider/audio-slider-img-1.png',
            title: 'তিন গোয়েন্দা',
            writer: 'রকিব হাসান',
            voice: 'রকিব হাসান তুষার',
            duration: '১:৪১ মিনিট',
        },
        {
            image: '/audioBook/demoCatImage/cover 1.jpg',
            title: 'তিন গোয়েন্দা',
            writer: 'রকিব হাসান',
            voice: 'রকিব হাসান তুষার',
            duration: '১:৪১ মিনিট',
        },
        {
            image: '/audioBook/audio-slider/audio-slider-img-1.png',
            title: 'তিন গোয়েন্দা',
            writer: 'রকিব হাসান',
            voice: 'রকিব হাসান তুষার',
            duration: '১:৪১ মিনিট',
        },
        {
            image: '/audioBook/audio-slider/audio-slider-img-2.png',
            title: 'তিন গোয়েন্দা',
            writer: 'রকিব হাসান',
            voice: 'রকিব হাসান তুষার',
            duration: '১:৪১ মিনিট',
        },
        {
            image: '/audioBook/audio-slider/audio-slider-img-3.png',
            title: 'তিন গোয়েন্দা',
            writer: 'রকিব হাসান',
            voice: 'রকিব হাসান তুষার',
            duration: '১:৪১ মিনিট',
        },
        {
            image: '/audioBook/audio-slider/audio-slider-img-4.png',
            title: 'তিন গোয়েন্দা',
            writer: 'রকিব হাসান',
            voice: 'রকিব হাসান তুষার',
            duration: '১:৪১ মিনিট',
        },
        {
            image: '/audioBook/demoCatImage/cover 1.jpg',
            title: 'তিন গোয়েন্দা',
            writer: 'রকিব হাসান',
            voice: 'রকিব হাসান তুষার',
            duration: '১:৪১ মিনিট',
        },
        {
            image: '/audioBook/audio-slider/audio-slider-img-1.png',
            title: 'তিন গোয়েন্দা',
            writer: 'রকিব হাসান',
            voice: 'রকিব হাসান তুষার',
            duration: '১:৪১ মিনিট',
        },
        {
            image: '/audioBook/demoCatImage/cover 1.jpg',
            title: 'তিন গোয়েন্দা',
            writer: 'রকিব হাসান',
            voice: 'রকিব হাসান তুষার',
            duration: '১:৪১ মিনিট',
        },
        {
            image: '/audioBook/audio-slider/audio-slider-img-1.png',
            title: 'তিন গোয়েন্দা',
            writer: 'রকিব হাসান',
            voice: 'রকিব হাসান তুষার',
            duration: '১:৪১ মিনিট',
        },
        {
            image: '/audioBook/audio-slider/audio-slider-img-2.png',
            title: 'তিন গোয়েন্দা',
            writer: 'রকিব হাসান',
            voice: 'রকিব হাসান তুষার',
            duration: '১:৪১ মিনিট',
        },
        {
            image: '/audioBook/audio-slider/audio-slider-img-3.png',
            title: 'তিন গোয়েন্দা',
            writer: 'রকিব হাসান',
            voice: 'রকিব হাসান তুষার',
            duration: '১:৪১ মিনিট',
        },
        {
            image: '/audioBook/audio-slider/audio-slider-img-4.png',
            title: 'তিন গোয়েন্দা',
            writer: 'রকিব হাসান',
            voice: 'রকিব হাসান তুষার',
            duration: '১:৪১ মিনিট',
        },
        {
            image: '/audioBook/demoCatImage/cover 1.jpg',
            title: 'তিন গোয়েন্দা',
            writer: 'রকিব হাসান',
            voice: 'রকিব হাসান তুষার',
            duration: '১:৪১ মিনিট',
        },
        {
            image: '/audioBook/audio-slider/audio-slider-img-1.png',
            title: 'তিন গোয়েন্দা',
            writer: 'রকিব হাসান',
            voice: 'রকিব হাসান তুষার',
            duration: '১:৪১ মিনিট',
        },
    ]
};
